FROM ruby:2.5.1

ARG MYSQL_PASSWORD
ENV MYSQL_PASSWORD $MYSQL_PASSWORD

RUN apt-get update \
    && apt-get upgrade -y \
    && mkdir -p /app
ADD . /app
WORKDIR /app
RUN bundle install --path vendor/bundle

CMD bundle exec rails server -e production
